"""empty message

Revision ID: 9d96250edd3c
Revises: d1fc0cc5a414
Create Date: 2018-11-14 22:18:06.090098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d96250edd3c'
down_revision = 'd1fc0cc5a414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'book', ['name'], unique=True)
    # ### end Alembic commands ###
